networks:
  internal:
    driver: bridge

services:
  server:
    build:
      args:
        ARCH: ${ARCH}
        TZ: ${TZ}
        DOCKER_IMAGE: ${DOCKER_IMAGE}
        FREERADIUS_VERSION: ${FREERADIUS_VERSION}
        USER_NAME: ${USER_NAME}
        GROUP_NAME: ${GROUP_NAME}
      context: Dockerfile
      dockerfile: server.dockerfile
    image: local/freeradius:${FREERADIUS_VERSION}
    volumes:
      - ./config/radiusd.conf:/usr/local/freeradius/etc/raddb/radiusd.conf:ro
      - ./config/clients.conf:/usr/local/freeradius/etc/raddb/clients.conf:ro
      - ./config/mods-config/files/authorize:/usr/local/freeradius/etc/raddb/mods-config/files/authorize:ro
      - ./config/mods-available/eap:/usr/local/freeradius/etc/raddb/mods-available/eap:ro
      - ./config/sites-available/default:/usr/local/freeradius/etc/raddb/sites-available/default:ro
      - ./config/sites-available/inner-tunnel:/usr/local/freeradius/etc/raddb/sites-available/inner-tunnel:ro
      - ./config/test/eap.conf:/app/eap.conf:ro
    networks:
      internal:
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
