client localhost {
  ipaddr = 127.0.0.1
  proto = udp
  secret = testing123
  nas_type = other
  require_message_authenticator = yes
  limit {
    max_connections = 16
    lifetime = 0
    idle_timeout = 900
  }
}
